linux-nvme/nvme-stas

- .github/workflows/meson-test.yml
- etc/dbus-1/system.d/meson.build
- etc/dbus-1/system.d/org.nvmexpress.stac.in.conf
- etc/dbus-1/system.d/org.nvmexpress.staf.in.conf
- meson.build
Fixed issues with GitHub workflows not finding python modules.
Fixed D-Bus issues raised by @igaw (see issues https://github.com/linux-nvme/nvme-stas/issues/3 and https://github.com/linux-nvme/nvme-stas/issues/4)
> Minor fixes related to integration with SuSE

- Dockerfile
> Fixing docker compilation error

- DISTROS.md
- README.md
- etc/dbus-1/system.d/org.nvmexpress.stac.in.conf
- etc/dbus-1/system.d/org.nvmexpress.staf.in.conf
- man/nvme-stas.xml
- man/stasadm.xml
- man/sys.conf.xml
- meson.build
- stacd.py
- stafd.py
- stasadm.py
- staslib/avahi.py
- staslib/stas.py
- sys.conf
> Perform explicit registration from user-space

- etc/dbus-1/system.d/org.nvmexpress.staf.in.conf
> Fix comments

- etc/dbus-1/system.d/org.nvmexpress.stac.in.conf
- etc/dbus-1/system.d/org.nvmexpress.staf.in.conf
> Changed DBus rules to only block setting properties

- DISTROS.md
- README.md
- etc/stas/stafd.conf
- man/stafd.conf.xml
- meson.build
- staslib/stas.py
> Simplifying mDNS configuration and updating documentation.

- .github/workflows/docker-publish.yml
- .github/workflows/meson-test.yml
> Fix GitHub workflows to pull from upstream libnvme

- Dockerfile
@martin-belanger please review
> Add missing openssl dependency to dockerfile

- stacd.py
- stafd.py
> LOG: enable libnvme debug when trace is enabled

- staslib/stas.py
> Use the newly added cntlrtype to check the type of controller

- DISTROS.md
> Update the Distro documentation

- Makefile
- staslib/stas.py
> When reading the Host NQN, warn people if the NQN seems invalid

- man/stacd.conf.xml
- man/stafd.conf.xml
- man/standard-conf.xml
> Adding man pages for ip-family and ignore-iface

- nvme-stas.spec.in
Add correct dependencies to RPM SPEC
Signed-off-by: Charles Rose <charles.rose@dell.com>
> nvme-stas.spec.in: Add package dependencies

- Makefile
- README.md
> rpm: add -ba to actually compile RPM from spec

- Makefile
- configure
> build: pass builddir to configure

- subprojects/libnvme.wrap
Update to v1.0-rc7 of libnvme.
Signed-off-by: Daniel Wagner <dwagner@suse.de>
> build: Update libnvme wrap

- README.md
> readme: Add github badges

- meson.build
- nvme-stas.spec.in
> Use one configuration_data object for everything.

- meson.build
> Add release candidate number to version string

- meson.build
> Set version to 1.0rc6

- meson.build
- stacctl.py
- stacd.py
- stafctl.py
- stafd.py
- stasadm.py
- staslib/avahi.py
- staslib/meson.build
- staslib/stas.py
- test/pylint.rc
> Linting and scrubbing the code

- .github/workflows/pylint.yml
compile meson 'libnvme' subproject
> lint: fix import error

- .github/workflows/pylint.yml
> ci: use pylint from python module

- .github/workflows/pylint.yml
> actions: unable to import certain modules

- meson.build
- staslib/meson.build
old code prevented tests to run correctly
> build: fix libnvme dependency

- .github/workflows/meson-test.yml
- meson.build
- staslib/meson.build
- staslib/stas.py
- staslib/version.py
> Add new unit tests

- meson.build
- staslib/meson.build
> unit tests: run pylint/pyflakes on groups of files instead of individually

- .dockerignore
> build: add docker ignore file

- meson.build
- test/meson.build
> test: move pylint/pyflakes defs to ./test/meson.build

- .github/workflows/meson-test.yml
- meson.build
- test/meson.build
> tests: fine tuning test environment.

- .github/workflows/docker-test.yml
> test: test docker compose up

- .github/workflows/docker-test.yml
> tests: load and install dependencies for docker tests

- Makefile
- nvme-stas.spec.in
Fix for issue https://github.com/linux-nvme/nvme-stas/issues/76
> build: fix "make rpm"

- .gitignore
> build: Add redhat-linux-build to .gitignore

- .github/workflows/meson-test.yml
- test/meson.build
- test/vermin-tools.conf
- test/vermin.conf
> tests: check minimum python version requirements (vermin)

- README.md
> doc: Add GitHub badges - "latest tag" and "commits since last tag"

- doc/api.rst
- doc/rst/org.nvmexpress.stac.debug.html
- doc/rst/org.nvmexpress.stac.html
- doc/rst/org.nvmexpress.staf.debug.html
- doc/rst/org.nvmexpress.staf.html
Used:
```
meson .build -Dman=true -Dhtml=true
meson compile -C .build
find .build/doc/ -maxdepth 1 -name '*.html' -exec cp {} doc/rst/ \;
```
> doc: add rst

- doc/man/meson.build
- meson.build
Generation of man/html pages got broken by a previous commit.
This patch fixes it.
> doc: fix man page generation

- doc/api.rst
- doc/quickstart.rst
> doc: expand api and quickstart rst with new files

- debian/copyright
- doc/conf.py
> doc: fix copyright

- test/meson.build
- test/test-config.py
- test/test-nvme_options.py
- test/test-transport_id.py
- test/test-udev.py
Added tests for theses classes: Udev, NvmeOptions, TransportId
> test: add more unit tests

- CONTRIBUTING.md
- Makefile
> doc: update CONTRIBUTING.md guidelines

- CONTRIBUTING.md
- Makefile
- doc/man/dbus-idl-to-docbooks.py
- stacctl.py
- stacd.py
- stafctl.py
- stafd.py
- stasadm.py
- staslib/avahi.py
- staslib/glibudev.py
- staslib/stas.py
- test/test-config.py
- test/test-nvme_options.py
- test/test-transport_id.py
- utils/nvmet/nvmet.py
Re-ran black with slightly different parameters.
> coding-style: fine tune black parameters

- doc/api.rst
> doc: add TOC to api.rst

- .coveragerc.in
- coverage.sh.in
- test/test-version.py
> test: add more coverage tests

- .coveragerc.in
- coverage.sh.in
- stacctl.py
- stafctl.py
- stafd.py
- staslib/avahi.py
- test/test-config.py
> test: adding more coverage test cases

- Makefile
> build: add 'uninstall' target

- coverage.sh.in
- doc/man/stacd.conf.xml
- etc/stas/stacd.conf
- stacd.py
- stafd.py
- staslib/stas.py
- test/test-config.py
> stacd: Add configuration parameter 'sticky-connections'

- NEWS.md
- doc/conf.py
- nvme-stas.spec.in
> release: complete version 1.1 documentation

- .github/workflows/pylint.yml
> test: more GitHub actions fixes

- NEWS.md
- doc/conf.py
- meson.build
> release 1.1.2

- stacd.py
- stafd.py
> stacd and stafd: add if name guardian to allow unit testing

- staslib/stas.py
- test/test-nvme_options.py
> Fixes IndexError Fixes #131

- test/meson.build
- test/test-controller.py
> tests: add controller test

- stacd.py
- staslib/avahi.py
- staslib/stas.py
- test/test-controller.py
Some of the GitHub Actions were failing due to problems with the test code itself
> test: fix GitHub actions

- docker-compose.yml
> test: add RUNTIME_DIRECTORY env. var. to docker-compose

- coverage.sh.in
- test/meson.build
- test/test-service.py
> tests: add service test

- coverage.sh.in
> test: fix coverage (undefined RUNTIME_DIRECTORY)

- stacd.py
- stafd.py
> stacd: fix defered call to remove_controller() with wrong arguments

- stafd.py
> test: fix pylint "Unused variable 'ex'"

- test/test-controller.py
> test: small fix

- staslib/stas.py
- test/test-service.py
> staslib: fix remove_controller with wrong argument

- staslib/stas.py
- test/test-nvme_options.py
> test: fix test for NvmeOptions failing on Fedora 34

- coverage.sh.in
- test/meson.build
- test/test-avahi.py
> test: add avahi

- test/test-avahi.py
> test: more avahi tests

- doc/man/stafd.service.xml
- doc/man/stas-config.target.xml
- doc/man/stas-config@.service.xml
- usr/lib/systemd/system/stacd.in.service
- usr/lib/systemd/system/stafd.in.service
> doc: document stas-config service/target.

- .coveragerc.in
- coverage.sh.in
- stacctl.py
- stafctl.py
- test/test-avahi.py
- test/test-nvme_options.py
> test: improve code coverage

- TESTING.md
> doc: Add TESTING.md

- TESTING.md
> doc: fix typos

- DISTROS.md
> doc: update system min. version requirement in DISTROS.md

- DISTROS.md
> doc: In DISTROS.md, add list of commands to print package version

- DISTROS.md
> doc: Fix GitHub markdown issue displaying pipe | character in code

- staslib/stas.py
> staslib: fix support for fibre channel

- NEWS.md
- doc/conf.py
- meson.build
> release: prepare v1.1.4 release

- stacd.py
- stafd.py
- staslib/avahi.py
- staslib/conf.py
- staslib/defs.py
- staslib/gutil.py
- staslib/log.py
- staslib/meson.build
- staslib/stas.py
- staslib/trid.py
- staslib/udev.py
- test/meson.build
- test/test-avahi.py
- test/test-config.py
- test/test-controller.py
- test/test-gtimer.py
- test/test-nvme_options.py
- test/test-transport_id.py
- test/test-udev.py
- usr/lib/systemd/system/stacd.in.service
- usr/lib/systemd/system/stafd.in.service
The following modules were created from stas.py.
- conf.py
- gutil.py
- log.py
- trid.py
- udev.py
> staslib: break stas.py into smaller modules

- stacd.py
- stafd.py
- staslib/avahi.py
- staslib/conf.py
- staslib/ctrl.py
- staslib/gutil.py
- staslib/log.py
- staslib/meson.build
- staslib/service.py
- staslib/singleton.py
- staslib/stas.py
- staslib/trid.py
- staslib/udev.py
- test/test-avahi.py
- test/test-config.py
- test/test-controller.py
- test/test-gtimer.py
- test/test-nvme_options.py
- test/test-service.py
- test/test-udev.py
> staslib: Use metaclass singleton pattern for singleton objects

- stacd.py
This happened when stacd tried to retrieve the log pages from stafd
over D-Bus just as stafd was shutting down. This resulted in an
unhandled D-Bus exception.
> stacd: Fix D-Bus race condition between stacd and stafd.

- coverage.sh.in
- stacd.py
- test/meson.build
- test/test-log.py
> test: add test for log.py module

- staslib/service.py
- test/test-controller.py
> test: fix broken test

- staslib/stas.py
Fix for issue: https://github.com/linux-nvme/nvme-stas/issues/180
> staslib: eliminate pcie from devices stacd will connect to

- NEWS.md
- doc/conf.py
- meson.build
> release: v1.1.5

- .github/dependabot.yml
> ci: add docker to dependabot.yml

- staslib/__init__.py
> test: fix pylint issues

- staslib/__init__.py
> test: fix typo

- NEWS.md
- doc/man/stacd.conf.xml
- etc/stas/stacd.conf
- staslib/conf.py
- staslib/ctrl.py
- test/test-config.py
- test/test-controller.py
> conf: Enable sticky-connections by default

- doc/rst/nvme-stas.html
- doc/rst/org.nvmexpress.stac.debug.html
- doc/rst/org.nvmexpress.stac.html
- doc/rst/org.nvmexpress.staf.debug.html
- doc/rst/org.nvmexpress.staf.html
- doc/rst/stacctl.html
- doc/rst/stacd.conf.html
- doc/rst/stacd.html
- doc/rst/stacd.service.html
- doc/rst/stafctl.html
- doc/rst/stafd.conf.html
- doc/rst/stafd.html
- doc/rst/stafd.service.html
- doc/rst/stas-config.target.html
- doc/rst/stas-config@.service.html
- doc/rst/stasadm.html
- doc/rst/sys.conf.html
> doc: update version number on html documents

- doc/man/stacd.conf.xml
- doc/rst/nvme-stas.html
- doc/rst/org.nvmexpress.stac.debug.html
- doc/rst/org.nvmexpress.stac.html
- doc/rst/org.nvmexpress.staf.debug.html
- doc/rst/org.nvmexpress.staf.html
- doc/rst/stacctl.html
- doc/rst/stacd.conf.html
- doc/rst/stacd.html
- doc/rst/stacd.service.html
- doc/rst/stafctl.html
- doc/rst/stafd.conf.html
- doc/rst/stafd.html
- doc/rst/stafd.service.html
- doc/rst/stas-config.target.html
- doc/rst/stas-config@.service.html
- doc/rst/stasadm.html
- doc/rst/sys.conf.html
> doc: Clarify that Hosts don't have access to Fabric Zoning configuration

- meson.build
> release: 1.2-rc2

- DISTROS.md
- NEWS.md
- doc/conf.py
- doc/man/stafd.conf.xml
- doc/rst/nvme-stas.html
- doc/rst/org.nvmexpress.stac.debug.html
- doc/rst/org.nvmexpress.stac.html
- doc/rst/org.nvmexpress.staf.debug.html
- doc/rst/org.nvmexpress.staf.html
- doc/rst/stacctl.html
- doc/rst/stacd.conf.html
- doc/rst/stacd.html
- doc/rst/stacd.service.html
- doc/rst/stafctl.html
- doc/rst/stafd.conf.html
- doc/rst/stafd.html
- doc/rst/stafd.service.html
- doc/rst/stas-config.target.html
- doc/rst/stas-config@.service.html
- doc/rst/stasadm.html
- doc/rst/sys.conf.html
- etc/stas/stacd.conf
- etc/stas/stafd.conf
- meson.build
- meson_options.txt
- staslib/conf.py
- staslib/ctrl.py
- subprojects/libnvme.wrap
> stafd: Add PLEO support

- doc/man/stafd.conf.xml
- staslib/ctrl.py
- staslib/service.py
> stacd: Restrict udev-rule=disabled to suppress TCP connections only

- doc/rst/nvme-stas.html
- doc/rst/org.nvmexpress.stac.debug.html
- doc/rst/org.nvmexpress.stac.html
- doc/rst/org.nvmexpress.staf.debug.html
- doc/rst/org.nvmexpress.staf.html
- doc/rst/stacctl.html
- doc/rst/stacd.conf.html
- doc/rst/stacd.html
- doc/rst/stacd.service.html
- doc/rst/stafctl.html
- doc/rst/stafd.conf.html
- doc/rst/stafd.html
- doc/rst/stafd.service.html
- doc/rst/stas-config.target.html
- doc/rst/stas-config@.service.html
- doc/rst/stasadm.html
- doc/rst/sys.conf.html
- meson.build
> release: v2.0-rc2

- staslib/ctrl.py
- staslib/service.py
> stafd: Always invoke Controller's reload_hdlr() on a reload command

- doc/rst/nvme-stas.html
- doc/rst/org.nvmexpress.stac.debug.html
- doc/rst/org.nvmexpress.stac.html
- doc/rst/org.nvmexpress.staf.debug.html
- doc/rst/org.nvmexpress.staf.html
- doc/rst/stacctl.html
- doc/rst/stacd.conf.html
- doc/rst/stacd.html
- doc/rst/stacd.service.html
- doc/rst/stafctl.html
- doc/rst/stafd.conf.html
- doc/rst/stafd.html
- doc/rst/stafd.service.html
- doc/rst/stas-config.target.html
- doc/rst/stas-config@.service.html
- doc/rst/stasadm.html
- doc/rst/sys.conf.html
> doc: Add/Update v1.1.6 HTML documentation

- .readthedocs.yaml
- doc/Makefile
- doc/conf.py.in
- doc/meson.build
- meson.build
> doc: Added .readthedocs.yaml

- .readthedocs.yaml
- doc/requirements.txt
> doc: Fix readthedocs dependencies

- .readthedocs.yaml
> doc: fix readthedocs dependencies (trial and error)

- meson.build
> doc: fix readthedocs dependencies (trial & error)

- doc/api.rst
- doc/quickstart.rst
> doc: fix *.html file location

- doc/man/html.xsl
> doc: Fix missing HTML links

- doc/conf.py.in
> doc: Set html_extra_path in the Sphinx conf.py file

- .readthedocs.yaml
- doc/conf.py.in
- doc/quickstart.rst
> doc: Convert html to rst

- .readthedocs.yaml
> read-the-docs: convert html to rst

- .readthedocs.yaml
- doc/quickstart.rst
> read-the-docs: Fix broken build

- NEWS.md
- meson.build
> release: v2.0-rc4

- NEWS.md
- meson.build
> release: v2.0-rc5

- meson_options.txt
- test/meson.build
> test: Make run-time dependencies for tests optional

- subprojects/libnvme.wrap
- test/meson.build
> release: Sync dependencies with newly released libnvme 1.2.

- staslib/udev.py
> staslib: Fix pyudev deadlock waiting for events forever loop.

- staslib/ctrl.py
- staslib/stas.py
- staslib/udev.py
- test/test-controller.py
> staslib: Minor cosmetic changes to debug messages

- meson.build
> release: Set version to 2.0

- utils/mk-discovery-conf.py
> utils: Add "Usage" to mk-discovery-conf.py

- staslib/udev.py
The `EnvironmentError` happens in bursts of thousands. So let's throttle the messages printed to the syslog.
> udev: Throttle EnvironmentError exception messages

- doc/man/dbus-idl-to-docbooks.py
- doc/man/meson.build
- stacd.py
- stafd.py
- staslib/stas.py
> staslib: Add load_idl() with multi Python versions support

- NEWS.md
- meson.build
- staslib/avahi.py
> Avahi: Allow uppercase/lowercase "NQN/nqn" key in TXT field

- coverage.sh.in
> test: Cosmetic changes to coverage log messages

- staslib/avahi.py
- staslib/conf.py
> staslib: Cosmetic changes (missing a space, move a comment)

- staslib/avahi.py
Needed for protocol=[roce | iwarp] which map to transport=rdma
> staslib: Add _proto2trans() to convert protocol to transport

- NEWS.md
- meson.build
> release: Preparing v2.1.2

- subprojects/libnvme.wrap
- test/test-log.py
Allow 100% coverage testing for module `log.py` by mocking class `systemd.journal.JournalHandler`
> test: Mock systemd.journal.JournalHandler()

- staslib/service.py
> staslib: Fix fallback udev rule

- CONTRIBUTING.md
- NEWS.md
- meson.build
- staslib/__init__.py
- Documentation clean-ups with regards to the usage of black as the code formatting tool.
- Remove module overload support (for now)
> Release 2.1.3-rc2

- .github/workflows/meson-test.yml
- .github/workflows/pylint.yml
Removing the step "apt-get update" from GitHub actions.
> test: GitHub Actions failing during "apt-get update"

- meson.build
- stacd.py
- stafd.py
- stasadm.py
- staslib/conf.py
- staslib/defs.py
- staslib/gutil.py
- staslib/service.py
- test/test-controller.py
- test/test-iputil.py
- test/test-timeparse.py
- utils/nvmet/loop.conf
- utils/nvmet/nvmet.py
Cleaning up definitions in defs.py. Adding support for loop device in nvmet.py.
> staslib: Just a bunch a minor clean-ups

- .github/workflows/meson-test.yml
GitHub actions keep getting broken upstream. apt-get update/upgrade/install keep being broken. Trying to work around the issue.
> test: Try to fix GitHub actions

- doc/dbus-idl-to-docbooks.py
- doc/stacd.service.xml
- doc/stafd.service.xml
- doc/stas-config.target.xml
- doc/stas-config@.service.xml
- meson.build
- test/meson.build
- usr/lib/systemd/system/meson.build
This is to address issue: https://github.com/linux-nvme/nvme-stas/issues/330
> Fix man pages

- staslib/singleton.py
- test/test-nvme_options.py
Previous tests were not really testing what we thought
> test: Improve NvmeOptions()

- test/test-udev.py
Fixes https://github.com/linux-nvme/nvme-stas/issues/407
> test: Fix test-udev with dummy interfaces

- .readthedocs.yaml
Previous changes seem to have broken read-the-docs
> Docs: Fix read-the-docs
