linux-nvme/nvme-stas

.github/workflows/meson-test.yml, meson.build
GitHub implements extra security when submitting a pull request, which prevents being able to read secrets. This is needed to access a private libnvme repo. Long story short, wokflows will always fail when triggered by a pull request. Hopefully, this will fix the issue.
=> Trying to fix workflow actions triggered by pull request

stafd.py
TP8010 was merged into upstream libnvme. Some APIs have changed.
This is to update nvme-stas to the new APIs.
=> Update libnvme APIs

docker-compose.yml
According to https://github.com/linux-nvme/nvme-stas/blob/main/DISTROS.md#things-to-do-post-installation
nvme-stas rely on libnvme
libnvme as well as nvme-cli rely on /etc/nvme/hostnqn and /etc/nvme/hostid
So we map the folder to the container
=> Mount /etc/nvme into docker compose

stacctl.py, stafctl.py
stafctl/stacctl would print cryptic exception messages on error. 
Now, a clearer message explaining what the problem is will be displayed.
=> Print descriptive message when unable to run stafctl/stacctl

.github/workflows/meson-test.yml, DISTROS.md, Dockerfile, README.md, debian/control, meson.build, stacd.py, stafd.py, staslib/stas.py
When the Avahi daemon detects Discovery Controllers over mDNS, it will report all IP address families (IPv4 and IPv6) being advertized. However, the host may not be configured to support all IP address families being advertized and should only try to connect with the IP address family that is supported for a given interface. This patch solves this issue.
=> Filter out invalid IP addresses.

etc/stas/stacd.conf, etc/stas/stafd.conf, staslib/stas.py
The configuration files offer two new options.
1) **ignore-iface** tells stafd/stacd not to use SO_BINDTODEVICE
2) **ip-family** tells stafd/stacd which IP address families to support
=> Add ignore-iface and ip-family config options

.github/workflows/meson-test.yml, DISTROS.md, Dockerfile, README.md, debian/control, meson.build, nvme-stas.spec.in, staslib/stas.py
This is to remove a dependency on python3-netifaces, which seems
to not be maintained anymore. Will have to revisit misconfiguration
checks in a future (yet to be determined) release.
=> Remove misconfiguration check

man/dbus-idl-to-docbooks.py, man/genlist-from-docbooks.py, nvme-stas.spec.in, stacctl.py, stacd.py, stafctl.py, stafd.py, stasadm.py, utils/nvmet/nvmet.py
I was looking at SuSE's and Red Hat's RPM spec files and wanted to align the sample spec file provided in the `nvme-stas` repo with that of the upstream projects. It is not 100% aligned because each distro has its own way of doing things, but at least the sample spec file is now a bit similar.
=> Aligning sample spec file with upstream spec files.

stacctl.py, stacd.py, stafctl.py, stafd.py, staslib/stas.py
Some of the DBus methods return json-formatted output. For some of
the methods, by making a few changes. it was possible to return
native DBus data (e.g. aa{ss}). Unfortunately, some methods return
data that is too complex to express as simple DBus data and the use
of Variants woulld be too complicated. Those methods will continue
to return data in json format, which allows more flexibility.
This addresses issue: https://github.com/linux-nvme/nvme-stas/issues/40
=> dbus: return native dbus data instead of json when possible.

etc/stas/stafd.conf, staslib/stas.py
The API `persistent_set()` from `libnvme` has absolutely no effect on connections. Most importantly, it does not set a default KATO on persistent Discovery Controller (DC) connections.
I/O Controller (IOC) connections, on the other hand, are assigned a default 2-minute KATO by the kernel regardless of `persistent_set()`.
Instead of calling `persistent_set()` (which, by the way, will be removed from `libnvme`), one should always set a default KATO on persistent DC connections. For IOC connections, however, setting a default KATO is optional because, as mentioned above, the kernel will assign one when not specified by the user.
=> Do not call libnvme's persistent_set()

staslib/defs.py, staslib/meson.build, staslib/stas.py, staslib/version.py
[PEP632](https://peps.python.org/pep-0632/) announces the deprecation of `distutils`. `nvme-stas` relies on `distutils.version.LooseVersion`, but none of the suggested replacements work as well as `distutils.version.LooseVersion` for handling Linux version strings such as `5.8.0-63-generic`.
This patch introduces the class `KernelVersion` that can be used to parse the Linux kernel version similar to how `LooseVersion` does it.
=> Remove deprecated distutils module

Makefile, nvme-stas.spec.in
The spec file got broken when I tried to align it with upstream
projects. So, I'm reverting some of the changes with this patch.
Related to: https://github.com/linux-nvme/nvme-stas/issues/76.
=> build: fix spec file

doc/meson.build, meson.build, test/meson.build
Per meson documentation, the default value for the run_command()
'check' parameter will be changed from 'false' to 'true' in a
future release of meson. To avoid problems when that change
happens, we explicitly use 'check: false' when invoking
run_command().
=> meson: explicitly set 'check: false' when invoking run_command()

staslib/meson.build
in staslib/meson.build, use "pure: true" with install_sources()
=> build: install staslib as pure

etc/stas/stacd.conf, stacd.py, staslib/stas.py
nvme-cli installs a udev rule (70-nvmf-autoconnect.rules) that is
used to automatically connect to I/O Controllers (IOC) as a result
of receiving an AEN indicating a change of Discovery Log Page
Entries (DLPE) from a Discovery Controller.
This udev rule creates a race condition with stafd/stacd who also
react to AENs to automatically connect to IOCs. This is not a
critical problem since the connections are successful and stacd is
designed to handle potential race conditions. However, error
messages may get printed to the syslog even though everything is
working fine.
This patch allows disabling the udev rule to eliminate the race
condition. The default is to leave the udev rule active and allow
for the race condition to happen. If a user gets annoyed by the
false error messages, they can …
=> stacd: allow disabling nvme-cli auto-connect udev rule.

doc/man/stacd.conf.xml, meson.build
The udev-rule option introduces a new feature not found in
previous versions. This is fully backwards compatible and will not
impact any existing features.
=> stacd: Document the udev-rule option and set version to 1.1

coverage.sh.in, stacd.py, stafd.py, staslib/avahi.py, staslib/stas.py, test/test-config.py, test/test-nvme_options.py, test/test-transport_id.py, test/test-udev.py
Coverage testing identified that atexit does not invoke clean up
methods for singleton objects on exit. Refactored singleton code
and added clean up methods that get explicitly called on exit.
=> staslib: better handling and clean up of singleton objects.

.github/workflows/meson-test.yml, doc/man/stacd.conf.xml, doc/man/stafd.conf.xml
Looks like package libsystemd-dev 3.16 was removed by GitHub. There
was no warning about this removal. Trying to perform a
"apt-get update/upgrade" to see if I can fix this issue.
=> test: fix github actions.

stacd.py
bug fix during object clean up. self._cfg_soak_tmr could be None.
=> stacd: 'NoneType' object has no attribute 'set_timeout'

test/test-config.py, test/test-transport_id.py, test/test-udev.py, test/test-version.py
example:
```
$ LD_LIBRARY_PATH=.build/subprojects/libnvme/src python3 -m unittest test/*.py
.................Udev.get_nvme_device() - Error: [Errno 2] No such file or directory: '/dev/bozo'
.........
----------------------------------------------------------------------
Ran 26 tests in 0.004s
OK
```
=> test: change if name guardian to allow manual test execution

staslib/stas.py
A callback function used to delete a Controller object was being
called by the Controller object that is being deleted resulting in
an exception. Controller._on_disconn_success() cannot invoke
disconnected_cb directly. It must instead schedule it through the
next idle main loop.
=> staslib: Fix cback function deleting object that called the cback.

stafd.py, staslib/stas.py
In hard to reproduce cases, the deletion of a controller may result
in the object being purged twice. This could have led to exceptions
=> staslib: fix race conditions during controller object removal.

usr/lib/systemd/system/meson.build, usr/lib/systemd/system/stacd.in.service, usr/lib/systemd/system/stafd.in.service, usr/lib/systemd/system/stas-config.in.target, usr/lib/systemd/system/stas-config@.service
This is a request from Red Hat for the case where nvme-stas is
copy-installed (e.g. pre-built rootfs image). In this case, nvme-
stas is not installed as a package. This means that the post-
install script doesn't get to run. The package post-install script
is where nvme-stas usually gets configured (i.e. /etc/nvme/hostnqn
and /etc/nvme/hostid get generated).
This patch allows generating /etc/nvme/hostnqn and /etc/nvme/hostid
at run time before stafd or stacd are started by systemd.
fixes issue: https://github.com/linux-nvme/nvme-stas/issues/130
=> install: add service to auto-generate hostnqn and hostid if missing

stacd.py, stafd.py, staslib/conf.py, staslib/defs.py, staslib/stas.py
In the recent reshuffling of the code to break stas.py into smaller
modules, the location of the sys.conf file (/etc/stas/sys.conf) got
lost.
=> conf: fix location of sys.conf

stacd.py, stafd.py, staslib/stas.py, test/test-controller.py, test/test-log.py
When running tests, we sometimes use fakefs to fake configuration
files such as /etc/nvme/hostnqn. It's important that the configuration
singletons such as conf.SysConf() do not get created before the fakefs
has been put in place otherwise the configuration will be wrong.
This was happening because "import stas" was actually initializing
the configuration before we had time to configure the fake fs. The
solution is to never implicitly intantiate singletons (such as
conf.SysConf()) during an "import", but rather explicitly instantiate
with a function call.
=> test: Fix problem between fakefs and when configuration gets loaded

stacd.py, stafd.py, staslib/conf.py, staslib/log.py, staslib/service.py, staslib/singleton.py, staslib/stas.py, test/test-config.py, test/test-controller.py, test/test-nvme_options.py, test/test-service.py
A recently introduced singleton pattern was using a weak reference
to keep track on object instances when it should have used a strong
reference. That was causing all kinds of crashes because singleton
object would suddenly be deleted w/o warning.
=> staslib: Fix broken singleton pattern

staslib/udev.py
Due to the recent changes to allow connecting to fibre channel
devices, an error was introduced in the I/O controller scanning
algorithm
=> udev: fix I/O controller scan & detect algorithm

.github/workflows/docker-publish.yml, Dockerfile, docker-compose.yml
they are no longer in use, this simplifies things a bit
=> docker: remove build args

NEWS.md, doc/conf.py, meson.build, stacd.py, staslib/ctrl.py, staslib/udev.py
1. Eliminate pcie devices from list of I/O controllers to audit
2. Add soaking timer to 'add events' to solve race condition with kernel
=> stacd: fix I/O controller connection audits

staslib/gutil.py
=> staslib: check that async operation hasn't been cancelled before proceeding

coverage.sh.in, stacd.py, stafd.py, staslib/__init__.py, staslib/avahi.py, staslib/ctrl.py, staslib/gutil.py, staslib/log.py, staslib/service.py, staslib/stas.py, staslib/trid.py, staslib/udev.py, test/test-controller.py, test/test-service.py
nvme-stas was designed with `libnvme` and the Linux kernel nvme driver in mind as the back-end driver. However, it should be possible to use a different driver such as the SPDK (https://github.com/spdk/spdk). 
This pull request refactors the code to allow code overrides so that one driver can easily be replaced by another.
=> Add ability to override linux-nvme driver by other drivers

subprojects/libnvme.wrap
libnvme 1.1 was just released. 
This pull request changes subprojects/libnvme.wrap to pull libnvme 1.1 instead of 1.0.
=> build: increase libnvme subproject revision number

doc/man/stacd.conf.xml, staslib/service.py
When disconnect-scope=all-connections-matching-disconnect-trtypes
and disconnect-trtypes=rdma+fc, stacd removes tcp connections when
it shouldn't.
=> stacd: fix bug disconnect-trtypes=rdma+fc

doc/man/stacd.conf.xml, etc/stas/stacd.conf, staslib/conf.py, test/test-config.py
1. Continue supporting "blacklist" even though it was replaced by "exclude".
2. Set "udev-rule" (back) to "enabled" by default.
=> config: Add backward compatibility support

doc/man/meson.build, meson.build, meson_options.txt, nvme-stas.spec.in, staslib/ctrl.py, test/meson.build
Meson only cares about build-time dependencies. Made the runtime dependencies optional.
=> build: Rework mesong dependencies

coverage.sh.in, staslib/avahi.py, staslib/conf.py, staslib/trid.py, test/test-transport_id.py
Fixe https://github.com/linux-nvme/nvme-stas/issues/271
=> staslib: Trim white spaces from transport identifiers

test/meson.build
Distros typically invoke meson with --wrap-mode=nodownload. E.g.
$ meson --wrap-mode=nodownload -Dman=true -Dhtml=true .build
This prevents downloading subprojects (in this case libnvme) which is required to run the unit test code.
This patch sets subproject()'s "required" flag to "false", which will allow the above meson command to run w/o errors.
=> build: Fix libnvme subproject dependency for distro builds

staslib/ctrl.py, staslib/trid.py, test/test-transport_id.py
The previous fix was trimming whitespaces too late leaving some data structures containing untrimmed strings. This moves the trimming at the point where DLPEs are received from libnvme and trims them right there and then.
=> staslib: Trim whitespaces at the source

NEWS.md, doc/conf.py, meson.build, staslib/avahi.py, staslib/conf.py, staslib/ctrl.py, staslib/udev.py
Parameters such as traddr, trsvcid, etc. may contain leading and/or trailing white spaces. These need to be trimmed.
=> staslib: Trim white spaces from DLPEs and manual configuration.

test/test-iputil.py
Link-local IPv6 addresses may appear on more than one interface. Therefore doing a reverse lookup on a link-local IPv6 address may return more than one interface, which will cause this unit test to fail. So, let's just eliminate link-local addresses from the test.
=> tests: Remove link-local addresses from unit tests

staslib/ctrl.py, staslib/service.py, staslib/stas.py
zeroconf (mDNS) Discovery Controllers that stop responding and for which mDNS discovery has also stopped responding, need to be removed after "zeroconf-connections-persistence" seconds. Found a problem in the logic that would cause the timeout to be mishandled.
=> stafd: Fix handling of lost zeroconf-discovered DC

test/test-config.py
=> test: Testing for _nvme-disc._tcp need to use assertIn()

staslib/avahi.py, staslib/conf.py
NVMe TP 8009 mentions using UDP for RoCE. However, nvme-stas currently registers for the TCP discovery service alone, and not UDP. So while avahi can see the RoCE service on the target, nvme-stas doesn't ask to be alerted to them. So update avahi to handle the same. Also, nvme-stas should convert p=roce in TXT to rdma when creating discovery controllers. And finally, ensure host-iface is avoided for RDMA controllers since it is not permitted in the kernel.
Signed-off-by: Martin George <marting@netapp.com>
=> staslib: fix RoCE support

.coveragerc.in, .github/workflows/docker-publish.yml, .github/workflows/docker-test.yml, .github/workflows/meson-test.yml, .github/workflows/pylint.yml, stacctl.py, stacd.py, stafctl.py, stafd.py, staslib/conf.py, staslib/ctrl.py, staslib/gutil.py, staslib/service.py, staslib/stas.py, staslib/timeparse.py, staslib/trid.py, test/test-avahi.py, test/test-config.py, test/test-controller.py, test/test-iputil.py
libnvme is not multi-thread safe. Since nvme-stas uses threads we need to make sure that each thread do not share the same libnvme context (i.e. root and host objects).
=> staslib: Fix memory corruption when running multiple threads

staslib/conf.py, staslib/iputil.py, staslib/udev.py, utils/nvmet/nvmet.conf
This is so that nvme-stas can better identify existing controller connections that can be reused for new candidate controllers.
More testing is needed. Just wanted to push the changes incrementally.
=> udev: improve comparison between candidate and existing controllers

NEWS.md, meson.build, stacctl.py, stacd.py, stafctl.py, stafd.py, staslib/avahi.py, staslib/conf.py, staslib/service.py, staslib/stacd.idl, staslib/stafd.idl, staslib/stas.py, staslib/trid.py, staslib/udev.py, test/test-controller.py, test/test-nbft.py, test/test-nbft_conf.py, test/test-service.py, test/test-transport_id.py, test/test-udev.py
When booting from SAN (BFS), the Host NQN specified in the NBFT files is often different from the Host NQN specified in /etc/nvme/hostnqn. Therefore, connections made after the system is fully booted will be made with a different Host NQN than the connections made during boot. nvme-stas did not consider the Host NQN when scanning for existing connections, which means that it would reuse a BFS connection when in fact it needed to create a new one using a different Host NQN.
Note that the same issue is seen in nvme-cli and libnvme as well. These will need to be fixed separately.
=> trid: Take Host NQN into account

staslib/udev.py
Optimize _process_udev_event() execution time to improve overall uevent handling.
=> udev: Optimize uevent handling

meson.build, staslib/meson.build, test/meson.build, test/pylint.rc
Speed up pylint by using `-j0` option and linting `staslib` as a package (directory with `__init__.py`) instead of individual modules.
=> test: Speed up pylint

test/test-defs.py
Different Python test frameworks manage Python processes differently when running tests. When running `python3 -m unittest` for instance, it looks like the same process executes all the tests.  Therefore when one test module T1 imports a module, the module is not re-imported if needed by T2.
This causes issues with test-defs.py which tries to mock the libnvme module. Indeed, when it is previously imported by staslib, the mocked libnvme module does not get re-imported.
This is an attempt to fix the test by removing staslib and staslib.defs from the imported modules before executing the test.
=> Attempt to fix the mock libnvme test so it works in GitHub actions & autopkgtest

test/test-udev.py
test-udev was failing when an interface had more than one IPv6 addresses assigned. This was due to the test checking that the number of assigned IPv6 addresses was exactly 1 (== 1) instead of checking greater-equal to 1 (>= 1).
=> test: Fix test-udev failing when multiple IPv6 addresses are used

staslib/iputil.py
On big-endian architectures (such as s390x), tests defined in test-iputil.py would hang:
```
596s test_get_interface (test-iputil.Test.test_get_interface)
10600s Check that get_interface() returns the right info ...
```
https://autopkgtest.ubuntu.com/results/autopkgtest-noble/noble/s390x/n/nvme-stas/20231128_021002_94626@/log.gz
Indeed, running the following hangs as well:
```python
from staslib import iputil
iputil.net_if_addrs()
```
This is an endianness issue that can be fixed by using native byte-ordering when packing and unpacking netlink data structures such as ifaddrmsg.
=> iputil: pack and unpack using native byte ordering

.github/workflows/meson-test.yml, .github/workflows/pylint.yml, .readthedocs.yaml, Makefile, README.md, TESTING.md, meson.build, utils/nvmet/nvmet.conf
The environment used to run GitHub actions has been updated upstream, which breaks the build. This is mainly due to the use of pip. That is, the use of upstream pip and not the one provided by Debian through apt-get install python3-pip.
This updates all the build scripts to use the standard Debian packages (if available) and not rely on "pip install".
=> Build: Fix Github actions

.readthedocs.yaml
Previous changes seem to have broken read-the-docs
=> Docs: Fix read-the-docs

.github/workflows/pylint.yml, coverage.sh.in, doc/standard-conf.xml, etc/stas/stacd.conf, staslib/conf.py, staslib/ctrl.py, staslib/gutil.py, staslib/trid.py, utils/nvmet/auth.conf, utils/nvmet/nvmet.py
This requires some changes in libnvme. Ref: https://github.com/linux-nvme/libnvme/pull/970
=> stacd: add authentication support (DHCHAP)
